            - name: Vercel Actions
  # You may pin to the exact commit or the version.
  # uses: nexterias/actions-vercel@cfcd6c1b67b27fb63ccd8ac2a1ee74ffb05aade9
  uses: nexterias/actions-vercel@v1.0.3
  with:
    # Vercel token: https://vercel.com/account/tokens
    token: 
    # Vercel project ID
    project-id: 
    # User ID within Vercel
    org-id: 
    # GitHub Token
    github-token: # optional
    # Create a production deployment
    production: # optional, default is false
    # Use the --prebuilt option
    prebuilt: # optional, default is false
    # Current Working Directory (default: process.cwd())
    cwd: # optional
    # Assign domains (multiple domains can be specified)
    domain-alias: # optional
    # Name for the target deployment environment
    github-deployment-environment: # optional
    # Deployment is public (`/_src` is exposed)
    public: # optional, default is false
    # Similar to env option but for build time only.
    build-env: # optional
    # Include an env var during run time
    env: # optional
          
